### ISSUE TITLE
bad number of fields in alignment line, but really not

### ISSUE THREAD

**Issue by Sanrrone** [fungs/taxator-tk#53]
Dears, I do the Usage tutorial for taxator-tk but the simplest way doing a blast a aligment:
`blastn -db db_Bnoti -outfmt '6 qseqid qstart qend qlen sseqid sstart send bitscore evalue nident length' -query 1.fa -num_threads 16 > test.tsv`

`head test.tsv`

> r2.1	1	183	183	gi|183207914|gb|CP000863.1|	2961553	2961371	339	1.72e-91	183	183
> r2.1	1	183	183	gi|347591739|gb|CP001937.1|	3049153	3048971	339	1.72e-91	183	183
> r2.1	1	183	183	gi|126385999|gb|CP000521.1|	2926476	2926294	333	8.02e-90	182	183
> r2.1	1	180	183	gi|169150821|emb|CU468230.2|	875172	875351	322	1.74e-86	178	180
> r2.1	1	178	183	gi|213985689|gb|CP001172.1|	995548	995725	313	1.04e-83	175	178
> r2.1	1	178	183	gi|169147133|emb|CU459141.1|	993447	993624	313	1.04e-83	175	178
> r2.1	1	178	183	gi|213054530|gb|CP001182.1|	3063964	3063787	313	1.04e-83	175	178
> r1.1	1	300	300	gi|213985689|gb|CP001172.1|	1181449	1181748	555	2.74e-156	300	300
> r1.1	1	300	300	gi|169147133|emb|CU459141.1|	1196738	1197037	555	2.74e-156	300	300
> r1.1	1	300	300	gi|213054530|gb|CP001182.1|	2863459	2863160	555	2.74e-156	300	30

check the mapping.tax:

> gi|68342549|gb|CP000076.1|	380021
> gi|47118328|dbj|BA000012.4|	381
> gi|310757913|gb|CP002287.1|	85698
> gi|507098404|emb|HE798385.1|	85698
> gi|359757955|gb|CP003150.1|	294
> gi|160361034|gb|CP000884.1|	80866
> gi|348031532|dbj|AP012280.1|	287
> gi|229359445|emb|AM181176.4|	294
> gi|566048795|gb|CP006958.1|	85698
> gi|218768969|emb|FM209186.1|	287

and then taxator-tk:
`cat test.tsv |~/programs/taxator-tk-master/bin/taxator -g mapping.tax -a n-best-lca -n 1`

but I give this error: 

> /home/ecastron/programs/taxator-tk-master/src/fileparser.hh(52): Throw in function FileParser<FactoryType>::RecordType* FileParser<FactoryType>::next() [with FactoryType = AlignmentRecordFactory<AlignmentRecordTaxonomy>; FileParser<FactoryType>::RecordType = AlignmentRecordTaxonomy]
> Dynamic exception type: boost::exception_detail::clone_impl<Exception>
> std::exception::what: std::exception
> [exception_tag_line*] = 1
> [exception_tag_general*] = bad number of fields in alignment line

I know that the error clearly refer to the alignment file (test.tsv), but I don't see the error, I had tried to delete "|" character as in the alignment file as mapping.tax but with no success.
what can i do?

PD:I attached the files that I use.
[files.tar.gz](https://github.com/fungs/taxator-tk/files/448068/files.tar.gz)

cheers

**Comment by fungs** [comment]
Sorry for the delay. Please try to add a tab at the end of the alignments. The current implementation expects a twelfth column. This is related to bug #52 and the fix will be in the next release.

**Comment by Sanrrone** [comment]
that was, thanks @fungs
