### ISSUE TITLE
refpack file

### ISSUE THREAD

**Issue by danshu** [fungs/taxator-tk#55]
Hi,

I learn from this page (https://github.com/fungs/taxator-tk/blob/master/USAGE.md) that "A refpack is a pre-built reference collection with a fitting taxonomy version and a corresponding mapping from sequence identifier to taxon ID. They can also be found in the RefSeq release catalogue but should be checked to match the actual taxonomy." 

Do you mean this file: "ftp://ftp.ncbi.nlm.nih.gov/refseq/release/release-catalog/release78.MultispeciesAutonomousProtein2taxname.corrected.gz" ?

Best,
Quan

**Comment by fungs** [comment]
Dear @danshu,

the file, which I referred to, in your case is:
ftp://ftp.ncbi.nlm.nih.gov/refseq/release/release-catalog/RefSeq-release78.catalog.gz

The README file in the same folder describes the TAB-separated columns of this gzipped text file:

> Columns:
>  1. taxonomy ID
>  2. species name
>  3. accession.version
>  4. gi
>  5. refseq release directory accession is included in
>       complete + other directories
>       '|' delimited
>  6. refseq status
>       na - not available; status codes are not applied to most genomic records
>       INFERRED
>       PREDICTED
>       PROVISIONAL
>       VALIDATED
>       REVIEWED
>       MODEL
>       UNKNOWN - status code not provided; however usually is provided for 
>                 this type of record
>  7. length

For example, a line looks like

`2       Bacteria        WP_000003344.1  445925489       bacteria|complete       UNKNOWN 127`

You need to know your FASTA identifiers, I usually shorten them to contain the accession like this, but you can also use the GI, if you like. Identifiers must be unique, must not contain spaces to work with all aligners and should be short to save space in the alignment files that are generated.

    >WP_000003344.1
    ATCG...

So in this example, you construct a mapping by extracting the third and the first columns of the release catalog. I usually do this using awk:

    zcat RefSeq-release78.catalog.gz | awk -F '\t' '{print $3 "\t" $1}' > mapping.tax.orig

So, the all-in-one procedure in shell would be:

    wget -q "ftp://ftp.ncbi.nlm.nih.gov/refseq/release/release-catalog/RefSeq-release78.catalog.gz" -O - | gzip -d | awk -F '\t' '{print $3 "\t" $1}' > mapping.tax

This will result in a mapping file for taxator-tk. However, you need to select a taxonomy for use which fits the mapping. As there is no directly usable version, you should select a release with a date similar to the release date of RefSeq and check/correct the taxid entries in the mapping. This is described in the USAGE.md file under "NCBI taxonomy".

**Comment by danshu** [comment]
Thanks for your detailed explanation, which is very useful.

**Comment by danshu** [comment]
Sorry that I have another question. I want to use last to do the alignments since my target file is large. I think I should use a fasta file containing the sequences for which I have corresponding accessions in the mapping file. I just don't know which file on the ncbi ftp site is the file I want.

Thanks,
Quan

**Comment by fungs** [comment]
As far as I know, you have to download multiple files from the FTP site (ftp://ftp.ncbi.nlm.nih.gov/refseq/release/). The sequences are organized in subfolders (bacteria, archaea etc.) and available in FASTA and GenBank formats. I usually download using some advanced ftp program like lftp/wget. Once on your hard disk, you can do

    zcat *.fna.gz > seqs.fna

to write everything into a single file.

I also recommend to shorten your mapping file to the sequences which you downloaded and you are actually using.

**Comment by danshu** [comment]
If I'm only interested in, for example, bacteria. Then I try to:
wget ftp://ftp.ncbi.nlm.nih.gov/refseq/release/bacteria/bacteria.*.genomic.fna.gz
zcat bacteria.*.genomic.fna.gz > bacteria.genomic.fna
lastdb bac_g_fna  bacteria.genomic.fna

Thanks for your help!

**Comment by fungs** [comment]
That's right. However, a few points to add:

* The LAST aligner is fast but needs much memory and time for building the index because it only runs on a single core. For the latest refpack, it took over a month to build the index. If you are only planing to use it once, better use blast
* If you shorten the FASTA IDs corresponding to the mapping and rename files in refpack format (download a small example refpack), the extended binary edition of taxator-tk contains scripts for building the aligner index, both with LAST and BLAST, out of the box
