### ISSUE TITLE
Why two input references?

### ISSUE THREAD

**Issue by ahl54** [fungs/taxator-tk#57]
[Taxator Workflow](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4380030/figure/btu745-F1/)

Why are two references given, one from the alignment and one input reference FASTA shown in the Workflow above? Does the second reference FASTA differ from the refpack?

For the megan-lca method, only the alignment is supplied, does RPA depend on the second input reference?

Thanks

**Comment by fungs** [comment]
Your are right, the (megan-)LCA only needs the alignments as input, which is a listing of where sequences match and the corresponding scores. The RPA needs to retrieve the corresponding parts of the sequences and thus requires the FASTA file.

The refpack contains both the reference FASTA file and taxonomy, so you only need to provide your metagenomic sequences in the form of a FASTA file when using the extended version of taxator-tk, which you can download from http://research.bifo.helmholtz-hzi.de/software/

Hope that answers your questions.

Cheers, Johannes
