### ISSUE TITLE
Missing compiler check for C++11 support

### ISSUE THREAD

**Issue by jpearl01** [fungs/taxator-tk#59]
Hello,

I'm running into a problem while trying to compile this:
[taxator-tk]$ ./build.sh
Running cmake
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.41.0
-- Found the following Boost libraries:
--   program_options
--   system
--   filesystem
--   thread
-- Configuring done
-- Generating done
-- Build files have been written to: /home/archana/apps/taxator-tk/Build-x86_64
Compiling source code in Build-x86_64
Scanning dependencies of target alignments-filter
[  4%] Building CXX object CMakeFiles/alignments-filter.dir/alignments-filter.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [CMakeFiles/alignments-filter.dir/alignments-filter.cpp.o] Error 1
make[1]: *** [CMakeFiles/alignments-filter.dir/all] Error 2
make: *** [all] Error 2

[taxator-tk]$ cat /etc/redhat-release
CentOS release 6.8 (Final)

[taxator-tk]$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[taxator-tk]$ cmake --version
cmake version 2.8.12.2

Boost version: 1.41.0

Any ideas as to the issue? 

Thanks in advance
~josh

**Comment by jpearl01** [comment]
Great, thanks so much.  I have a more recent compiler, but I think I'll go for the easier route of just using the precompiled binaries - they appear to be working for me, at least on first blush.

~josh

**Comment by fungs** [comment]
Yes, thanks! I will try to fix this for the next major update.

**Comment by fungs** [comment]
We now moved to C++14 and have this checked in cmake during build using

    set(CMAKE_CXX_STANDARD 14)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
    set(CMAKE_CXX_EXTENSIONS OFF)

This issue should be fixed.
