### ISSUE TITLE
Compiling failed 1.3.3

### ISSUE THREAD

**Issue by EacoChen** [fungs/taxator-tk#64]
Hi,

I installed the pre-compiled 1.3.3e and I ran taxator. It showed:

"taxator: error while loading shared libraries: libdl.so.2: wrong ELF class: ELFCLASS32"
 
I used the `strace `which taxator``

it shows use the system /usr/lib which is 32 library, and the system 64 library is in /usr/lib64,

I tried to export that library path like `export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib64,
But it didn't work.

so I tried to compile the taxator by myself

but I meet some mistake:

./build.sh
"Running cmake
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /users/bin/x86_64-conda-linux-gnu-cc
-- Check for working C compiler: /users/bin/x86_64-conda-linux-gnu-cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /users/bin/x86_64-conda-linux-gnu-c++
-- Check for working CXX compiler: /users/bin/x86_64-conda-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   program_options
--   system
--   filesystem
--   thread
-- Configuring done
-- Generating done
-- Build files have been written to: /users/src/taxator-tk/core/bin
Compiling source code in bin
make[1]: Entering directory '/users/src/taxator-tk/core/bin'
make[2]: Entering directory '/users/src/taxator-tk/core/bin'
Scanning dependencies of target alignments-filter
make[2]: Leaving directory '/users/src/taxator-tk/core/bin'
make[2]: Entering directory '/users/src/taxator-tk/core/bin'
[  4%] Building CXX object CMakeFiles/alignments-filter.dir/alignments-filter.cpp.o
[  8%] Building CXX object CMakeFiles/alignments-filter.dir/src/alignmentrecord.cpp.o
[ 12%] Building CXX object CMakeFiles/alignments-filter.dir/src/accessconv.cpp.o
Linking CXX executable alignments-filter
make[2]: Leaving directory '/users/src/taxator-tk/core/bin'
[ 37%] Built target binner
make[2]: Entering directory '/users/src/taxator-tk/core/bin'
Scanning dependencies of target taxator
make[2]: Leaving directory '/users/src/taxator-tk/core/bin'
make[2]: Entering directory '/users/src/taxator-tk/core/bin'
[ 41%] Building CXX object CMakeFiles/taxator.dir/taxator.cpp.o
In file included from /users/src/taxator-tk/core/src/taxonpredictionmodelsequence.hh:37:0,
                 from /users/src/taxator-tk/core/taxator.cpp:36:
/users/src/taxator-tk/core/src/sequencestorage.hh: In constructor 'RandomInmemorySeqStoreRO<StorageStringType, Work
ingStringType, Format>::RandomInmemorySeqStoreRO(const string&, const std::set<std::__cxx11::basic_string<char> >&)':
/users/src/taxator-tk/core/src/sequencestorage.hh:96:57: error: no matching function for call to 'std::__cxx11::bas
ic_string<char>::c_str(seqan::Value<seqan::StringSet<seqan::String<char, seqan::Alloc<> > >, 0>::Type&)'
             if ( whitelist.count( std::string::c_str(*id) )) {
                                                         ^
In file included from /users/x86_64-conda-linux-gnu/include/c++/7.5.0/string:52:0,
                 from /users/include/boost/thread/exceptions.hpp:20,
                 from /users/include/boost/thread/pthread/thread_data.hpp:10,
                 from /users/include/boost/thread/thread_only.hpp:17,
                 from /users/include/boost/thread/thread.hpp:12,
                 from /users/include/boost/thread.hpp:13,
                 from /users/src/taxator-tk/core/taxator.cpp:21:
/users/x86_64-conda-linux-gnu/include/c++/7.5.0/bits/basic_string.h:2280:7: note: candidate
: const _CharT* std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::c_str() const [with _CharT = char; _Traits = std::char_traits<cha
r>; _Alloc = std::allocator<char>]
       c_str() const _GLIBCXX_NOEXCEPT
       ^~~~~
/usersx86_64-conda-linux-gnu/include/c++/7.5.0/bits/basic_string.h:2280:7: note:   candida
te expects 0 arguments, 1 provided
make[2]: *** [CMakeFiles/taxator.dir/build.make:59: CMakeFiles/taxator.dir/taxator.cpp.o] Error 1
make[2]: Leaving directory '/users/PMIU0100/chenhy520/src/taxator-tk/core/bin'
make[1]: *** [CMakeFiles/Makefile2:134: CMakeFiles/taxator.dir/all] Error 2
make[1]: Leaving directory '/users/PMIU0100/chenhy520/src/taxator-tk/core/bin'
make: *** [Makefile:76: all] Error 2

how to solve this problem.

**Comment by fungs** [comment]
Hi, for the first error, you are right that the pre-compiled version is 64bit, compiled on Debian/Ubuntu. It seems to have problems with the mixed bit user libraries.

For the compilation, please make sure that you are using the source code for the last release 1.3.3. There is a now version 1.4.x coming soon which needed larger changes and preparations. To me it seems, like you are building from the code in master branch, which contains later changes.

Once you have built the binaries using the correct source code, you should be able to copy them into the extended version bin folder and use the pipelines as intended (if none of the other 64 bit binaries give you trouble).

Best,
Johannes

**Comment by EacoChen** [comment]
Thank you so much for reply.

My linux is redhat, which may be cause the problem.
I downloaded the last release 1.3.3 source code and compile it use `./build.sh`. And it worked.

Thank you again.
